apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 120s
      evaluation_interval: 120s

    # Emplacement des règles d'alerte
    rule_files:
      - "/etc/prometheus/rules/security-alerts.yml"

    scrape_configs:
      - job_name: 'microservice-security'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['microservice-securit:8070']
            labels:
              application: 'microservice-securit'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-alerts
data:
  security-alerts.yml: |
    groups:
      - name: microservice-security-alerts
        rules:
          - alert: MicroserviceSecurityHigh401Errors
            expr: rate(http_server_requests_seconds_count{application="microservice-security", status="401"}) 
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Taux d'erreurs 401 élevé sur le microservice security"
              description: "Le microservice security retourne plus de 5 erreurs 401 par minute pendant plus de 2 minutes."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-service
  template:
    metadata:
      labels:
        app: prometheus-service
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            # Monte la config principale
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            # Monte le fichier d'alertes
            - name: prometheus-rules
              mountPath: /etc/prometheus/rules
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-rules
          configMap:
            name: security-alerts

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus-service
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 9090
  type: LoadBalancer